/**
 * A selection of abilities and skills from the O*NET 24.3 Database, sponsored
 * by the U.S. Department of Labor, Employment and Training Administration.
 *
 * The database is licensed under a Creative Commons Attribution 4.0
 * International License.
 *
 * {@link https://www.onetcenter.org/license_db.html}
 */
export const abilitiesAndSkills: string[] = [
  'Active Learning',
  'Active Listening',
  'Arm-Hand Steadiness',
  'Auditory Attention',
  'Category Flexibility',
  'Complex Problem Solving',
  'Control Precision',
  'Coordination',
  'Critical Thinking',
  'Deductive Reasoning',
  'Depth Perception',
  'Dynamic Flexibility',
  'Dynamic Strength',
  'Equipment Maintenance',
  'Equipment Selection',
  'Explosive Strength',
  'Extent Flexibility',
  'Far Vision',
  'Finger Dexterity',
  'Flexibility of Closure',
  'Fluency of Ideas',
  'Glare Sensitivity',
  'Gross Body Coordination',
  'Gross Body Equilibrium',
  'Hearing Sensitivity',
  'Inductive Reasoning',
  'Information Ordering',
  'Installation',
  'Instructing',
  'Judgment and Decision Making',
  'Learning Strategies',
  'Management of Financial Resources',
  'Management of Material Resources',
  'Management of Personnel Resources',
  'Manual Dexterity',
  'Mathematical Reasoning',
  'Mathematics',
  'Memorization',
  'Monitoring',
  'Multilimb Coordination',
  'Near Vision',
  'Negotiation',
  'Night Vision',
  'Number Facility',
  'Operation and Control',
  'Operation Monitoring',
  'Operations Analysis',
  'Oral Comprehension',
  'Oral Expression',
  'Originality',
  'Perceptual Speed',
  'Peripheral Vision',
  'Persuasion',
  'Problem Sensitivity',
  'Programming',
  'Quality Control Analysis',
  'Rate Control',
  'Reaction Time',
  'Reading Comprehension',
  'Repairing',
  'Response Orientation',
  'Science',
  'Selective Attention',
  'Service Orientation',
  'Social Perceptiveness',
  'Sound Localization',
  'Spatial Orientation',
  'Speaking',
  'Speech Clarity',
  'Speech Recognition',
  'Speed of Closure',
  'Speed of Limb Movement',
  'Stamina',
  'Static Strength',
  'Systems Analysis',
  'Systems Evaluation',
  'Technology Design',
  'Time Management',
  'Time Sharing',
  'Troubleshooting',
  'Trunk Strength',
  'Visual Color Discrimination',
  'Visualization',
  'Wrist-Finger Speed',
  'Writing',
  'Written Comprehension',
  'Written Expression',
];
