/**
 * A selection of skills from The Sims, a popular video game series developed by
 * Maxis and published by Electronic Arts.
 *
 * {@link https://en.wikipedia.org/w/index.php?title=The_Sims&oldid=967293808}
 *
 * {@link https://sims.fandom.com/wiki/Skill?oldid=921991}
 *
 * {@link https://sims.fandom.com/wiki/Secret_skill?oldid=921396}
 */
export const skills: string[] = [
  'Acting',
  'Air Guitar',
  'Alchemy',
  'Anger Management',
  'Archaeology',
  'Baking',
  'Ball Fighting',
  'Ballet',
  'Bass',
  'Blocks',
  'Bot Building',
  'Bowling',
  'Broom Riding',
  'Bubble Blowing',
  'Bug Eating',
  'Charisma',
  'Chess',
  'Cleaning',
  'Club Dancing',
  'Collecting',
  'Comedy',
  'Communication',
  'Consignment',
  'Cooking',
  'Couple Counselling',
  'Creativity',
  'Dancing',
  'Darts',
  'Diving',
  'DJ Mixing',
  'Dominoes',
  'Drafting',
  'Driving',
  'Drums',
  'Entertainer',
  'Fabrication',
  'Fairy Magic',
  'Fire Prevention',
  'Firewalking',
  'Fishing',
  'Flower Arranging',
  'Foosball',
  'Gambling',
  'Gardening',
  'Golfing',
  'Gourmet Cooking',
  'Guitar',
  'Hacking',
  'Handiness',
  'Herbalism',
  'Homework',
  'Hopscotch',
  'Horseshoes',
  'Hunting',
  'Imagination',
  'Inventing',
  'Juice Fizzing',
  'Juice Pong',
  'Jumping',
  'Karaoke',
  'Knitting',
  'Lifelong Happiness',
  'Logic',
  'Lycantropy',
  'Magic',
  'Martial Arts',
  'Media Production',
  'Meditation',
  'Mischief',
  'Mixology',
  'Nectar Making',
  'Nursery Rhyme',
  'Painting',
  'Parenting',
  'Performance Artist',
  'Pet Training',
  'Photography',
  'Physiology',
  'Piano',
  'Ping Pong',
  'Pipe Organ',
  'Racing',
  'Research & Debate',
  'Riding',
  'Robotics',
  'Rock Climbing',
  'Rocket Science',
  'Rubble Clearing',
  'Sales',
  'Scouting',
  'Scuba Diving',
  'Sculpting',
  'Shuffleboard',
  'Singing',
  'Skating',
  'Snake Charming',
  'Snowboarding',
  'Social Networking',
  'Spellcasting',
  'Street Art',
  'Styling',
  'Tai Chi',
  'Talking',
  'Tattooing',
  'Thinking',
  'Trampoline',
  'Veterinarian',
  'Video Gaming',
  'Violin',
  'Walking',
  'Waterskiing',
  'Wellness',
  'Wildlife',
  'Windsurfing',
  'Work Ethic',
  'Xylophone',
  'Yoga',
];
