/**
 * Sampling of Vocational Education and Training courses in Australia from the
 * National Centre for Vocational Education Research's 2018 data slicer.
 *
 * Skill sets, graduate certificates, and graduate diplomas have been stripped
 * for simplicity.
 *
 * {@link https://www.ncver.edu.au/research-and-statistics/data/all-data/total-vet-students-and-courses-2018-data-slicer}
 *
 * The data is provided under a Creative Commons Attribution 3.0 Australia
 * International License.
 *
 * {@link https://www.ncver.edu.au/copyright}
 */

import type { EducationQualification } from '../../types.js';

export const certificate1s: EducationQualification[] = [
  'Aboriginal and Torres Strait Islander Language and Knowledge Work',
  'Aboriginal Language/s',
  'Access to Work and Training (Introductory)',
  'Active Volunteering',
  'AgriFood Operations',
  'Animal Studies',
  'Automotive',
  'Aviation (Foundation Skills)',
  'Basic English Language Skills',
  'Conservation and Land Management',
  'Core Skills for Employment and Training - Communication',
  'Dance',
  'Defence Force Cadets',
  'Engineering',
  'English Proficiency',
  'Financial Services',
  'Fishing Operations',
  'Food Processing',
  'French',
  'Functional Literacy',
  'Fundamental Aboriginal Languages for Personal Use',
  'Fundamental English for Speakers of Other Languages',
  'General Education for Adults (Introductory)',
  'Horticulture',
  'Hospitality (Kitchen Operations)',
  'Information Technology',
  'Initial Adult Literacy and Numeracy',
  'Japanese',
  'Leadership',
  'Local Government (Operational Works)',
  'Logistics',
  'Manufacturing (Pathways)',
  'Maritime Operations (Coxswain Grade 2 Near Coastal)',
  'Meat Processing (Meat Retailing)',
  'Pharmaceutical Manufacturing',
  'Plumbing Services',
  'Preparation for Work and Training',
  'Racing (Stablehand)',
  'Resources and Infrastructure Operations',
  'Retail Operations',
  'Seafood Processing',
  'Security Operations',
  'Skills for Education and Training Pathways',
  'Skills for Vocational Pathways',
  'Vocational Access',
  'Vocational Preparation',
  'Wider Opportunities for Work (WOW)',
  'Work Education',
  'Work Preparation (Community services)',
  'Workplace Environmental Responsibilities',
].map(
  (area) =>
    ({
      countries: ['au'],
      level: 2,
      name: `Certificate I in ${area}`,
    }) as const,
);

export const certificate2s: EducationQualification[] = [
  'Active Volunteering',
  'Automotive Body Repair Technology',
  'Automotive Manufacturing Production - Passenger Motor Vehicle',
  'Automotive Studies (Pre-vocational)',
  'Automotive Tyre Servicing Technology',
  'Automotive Underbody Technology',
  'Aviation (Flight Operations-Cargo Services)',
  'Aviation (Flight Operations)',
  'Boating Services',
  'Clothing Production (Intermediate)',
  'Community Engagement',
  'Community Health Research',
  'Continence Promotion and Care',
  'Drilling Operations',
  'Driver Competence',
  'Driving Operations',
  'Electronic Assembly',
  'Engineering Studies',
  'Equine Industry',
  'Explosive Ordnance',
  'Foreign Language Studies',
  'French',
  'Further Study Skills',
  'German',
  'Health Support Services',
  'Horticulture (Arboriculture)',
  'Laundry Operations',
  'Leadership Development',
  'Motorsport Technology',
  'Music Industry',
  'Nail Technology',
  'Population Health',
  'Process Manufacturing',
  'Production Horticulture',
  'Public Safety (Firefighting and Emergency Operations)',
  'Recreational Vehicle Manufacturing',
  'Security Operations',
  'Shunting',
  'Sport Coaching',
  'Telecommunications Digital Reception Technology',
  'Transmission Structure and Line Assembly',
  'Transport & Distribution (Coastal Maritime Operations - Coxswain)',
  'Transport and Logistics (Warehousing and Storage)',
  'Underground Metalliferous Mining',
  'Understanding and Management of Diabetes',
  'Warehousing Operations',
  'Waste Management',
  'Water Operations',
  'Wine Industry Operations',
  'Work Preparation',
].map(
  (area) =>
    ({
      countries: ['au'],
      level: 2,
      name: `Certificate II in ${area}`,
    }) as const,
);

export const certificate3s: EducationQualification[] = [
  'Appliance Service',
  'Automotive (Mechanical - Light Vehicle)',
  'Automotive and Marine Trimming Technology',
  'Automotive Manufacturing Technical Operations - Bus, Truck and Trailer',
  'Automotive Specialist',
  'Business Administration',
  'Business to Business Sales',
  'Civil Foundations',
  'Construction Crane Operations',
  'Cotton Ginning',
  'Data and Voice Communications',
  'Design Fundamentals',
  'Engineering - Production Systems',
  'ESI - Distribution',
  'Fitness',
  'Forest Growing and Management',
  'Formwork/Falsework',
  'Glass and Glazing',
  'Guiding',
  'Heavy Commercial Vehicle Mechanical Technology',
  'Heritage Locomotive Assistant or Steam Locomotive Fireman',
  'Home and Community Care',
  'Horticulture (Landscape)',
  'Information Technology (General)',
  'Jewellery Manufacture',
  'Marine',
  'Mattress and Base Making',
  'Mechanical Rail Signalling',
  'Mobile Crane Operations',
  'Outdoor Power Equipment Technology',
  'Pathology Collection',
  'Pest Management',
  'Property Services (Operations)',
  'Public Safety (Aquatic Search and Rescue)',
  'Recreational Vehicle Service and Repair',
  'Refrigeration and Air-Conditioning',
  'Retail Baking (Combined)',
  'Roof Plumbing',
  'Sawmilling and Processing',
  'School Support Services',
  'Security Operations',
  'Signs and Graphics',
  'Social Housing',
  'Telecommunications',
  'Terminal Train Driving',
  'Tourism (Tour Wholesaling)',
  'Tourism',
  'Transport and Logistics (Road Transport)',
  'Watch and Clock Service and Repair',
  'Woodmachining',
].map(
  (area) =>
    ({
      countries: ['au'],
      level: 3,
      name: `Certificate III in ${area}`,
    }) as const,
);

export const certificate4s: EducationQualification[] = [
  'Aboriginal Performance',
  'Anaesthetic Technology',
  'Animal Control and Regulation',
  'Arts Administration',
  'Aviation (Aviation Supervision)',
  'Building Biology',
  'Business (Governance)',
  'Business and Personal Coaching',
  'Child, Youth and Family Intervention (residential and out of home care)',
  'Commercial Cookery',
  'Compliance and Risk Management',
  'Conservation and Land Management',
  'Contemporary Pilates & Teaching Methodology',
  'Coordination of volunteer programs',
  'Court Operations',
  'Digital Media Technologies',
  'Electrical - Photovoltaic systems',
  'English Proficiency - ESL',
  'Environmental Management',
  'Finance and Mortgage Broking',
  'General Insurance',
  'Government (Investigation)',
  'Government (Project Management)',
  'Government (Revenue Administration)',
  'Government Security',
  'Health Science Foundations',
  'Hospitality (Patisserie)',
  'Hyperbaric Operations (Diver Medical Technician)',
  'Information Technology (Technical Support)',
  'International Freight Forwarding (Senior Operator)',
  'Local Government (Planning)',
  'Marketing and Communication',
  'Parent, Family and Community Engagement',
  'Personal Injury Management (ReturntoWork)',
  'Pharmaceutical Manufacturing',
  'Pilates Matwork and Reformer',
  'Printing and Graphic Arts',
  'Public Safety (Community Safety)',
  'Rail Safety Investigation',
  'Recordkeeping',
  'Seafood Processing',
  'Shared Technology',
  'Sound Production',
  'Surface Extraction Operations',
  'Teaching an Endangered Aboriginal Language',
  'Telecommunications Engineering Technology',
  'Telecommunications Networks Technology',
  'Timber Truss and Frame Design',
  'Underground Coal Operations',
  'Visual Arts',
].map(
  (area) =>
    ({
      countries: ['au'],
      level: 4,
      name: `Certificate IV in ${area}`,
    }) as const,
);

export const diplomas: EducationQualification[] = [
  'Accounting',
  'Aeroskills (Avionics)',
  'Applied Fashion Design and Technology',
  'Automotive Management',
  'Aviation (Aviation Management)',
  'Biblical Ministry',
  'Business Administration',
  'Carbon Management',
  'Christian Missions Leadership',
  'Clinical Hypnotherapy',
  'Clinical Pilates',
  'Community Health',
  'Consultancy',
  'Engineering Technology',
  'Financial Counselling',
  'Fire Systems Design',
  'Fitness Coaching',
  'General Insurance',
  'Geoscience',
  'Horse Breeding (Stud Management)',
  'Information Technology',
  'Insurance Broking',
  'Laboratory Technology',
  'Landscape Design',
  'Leadership Coaching and Mentoring',
  'Leadership in Expressive Arts and Group Work',
  'Life Coaching',
  'Local Government (Elected Member)',
  'Maintenance Management',
  'Nursing (Enrolled/Division 2 nursing)',
  'Ornamental Horticulture',
  'Paramedical Science (Ambulance)',
  'Paramedical Science (Anaesthesia)',
  'Pilates Movement Therapy',
  'Printing and Graphic Arts (Multimedia)',
  'Printing and Graphic Arts',
  'Professional Practice Management',
  'Property Services (Asset and Facility Management)',
  'Rehabilitation',
  'Retail Leadership',
  'Share Trading and Investment',
  'Social Housing',
  'Superannuation',
  'Surface Operations Management',
  'Sustainability',
  'Tertiary Preparation',
  'Theatre Arts',
  'Tourism',
  'Training Design and Development',
  'Venues and Events',
].map(
  (area) =>
    ({
      countries: ['au'],
      level: 5,
      name: `Diploma of ${area}`,
    }) as const,
);

export const advancedDiplomas: EducationQualification[] = [
  'Advertising',
  'Aeronautics - Airline Transport Pilot',
  'Air-conditioning and Refrigeration Engineering',
  'Arts (Acting)',
  'Business',
  'Christian Ministry and Theology',
  'Clinical Hypnotherapy',
  'Community Sector Management',
  'Conservation and Land Management',
  'Disability Work',
  'Electrical - Engineering',
  'Electronics and Communications Engineering',
  'Engineering - Explosion protection',
  'Engineering (Oil and Gas)',
  'Engineering Technology - Renewable Energy',
  'Events',
  'Extractive Industries Management',
  'Fashion and Textile Design',
  'Film Television and Theatre Acting',
  'Government (Procurement and Contracting)',
  'Government (Workplace inspection/ Investigations/Fraud control)',
  'Group Facilitation',
  'Homoeopathy',
  'Industrial Automation',
  'International Business Management',
  'International Business',
  'Jewellery and Object Design',
  'Journalism',
  'Justice',
  'Legal Practice',
  'Management (Human Resources)',
  'Maritime Operations (Marine Engineering Class 1)',
  'Metalliferous Mining',
  'Multimedia',
  'Music Theatre',
  'Performance',
  'Police Investigation',
  'Program Management',
  'Public Safety (Firefighting Management)',
  'Rudolf Steiner Education',
  'Share Trading and Investment',
  'Stage Management',
  'Surveying',
  'Tourism',
  'Traditional Chinese Medicine',
  'Transpersonal Art Therapy',
  'Travel and Tourism Management',
  'Travel and Tourism',
  'Visual Communication (Design Communication / Photo Communication)',
  "Children's Services",
].map(
  (area) =>
    ({
      countries: ['au'],
      level: 5,
      name: `Advanced Diploma of ${area}`,
    }) as const,
);
